sudo: required

services: docker

env:
  matrix:
    - VERSION=11.0
    - VERSION=11.0 FULL=True
    - VERSION=10.0
    - VERSION=10.0 FULL=True
    - VERSION=9.0
    - VERSION=9.0 FULL=True

script:
  - make VERSION=$VERSION FULL=$FULL build
  - make VERSION=$VERSION FULL=$FULL test

after_success:
  - travis/publish.sh
