sudo: required

services: docker

env:
  matrix:
    - VERSION=11.0
    - VERSION=10.0
    - VERSION=9.0

script:
  - make VERSION=$VERSION build
  - make VERSION=$VERSION FULL=$FULL build
  - make VERSION=$VERSION FULL=$FULL test

after_success:
  - travis/publish.sh
  - FULL=True bash -c 'travis/publish.sh'
